// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXpdmTUPhrbhPO9rUDAeGf-bea0SRQQA',
    appId: '1:985947424591:web:f0debf0851748a2249e73a',
    messagingSenderId: '985947424591',
    projectId: 'saglamuglumuhasebe',
    authDomain: 'saglamuglumuhasebe.firebaseapp.com',
    storageBucket: 'saglamuglumuhasebe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNlCUwIV2H3FrrBTNnkKyj9G7Cv7a0rWI',
    appId: '1:985947424591:android:95d486ae4c16ae8949e73a',
    messagingSenderId: '985947424591',
    projectId: 'saglamuglumuhasebe',
    storageBucket: 'saglamuglumuhasebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-bVy6JD6i8YBnsXFEsdOs9mUky-x2uQ',
    appId: '1:985947424591:ios:6ecca0f639550b7d49e73a',
    messagingSenderId: '985947424591',
    projectId: 'saglamuglumuhasebe',
    storageBucket: 'saglamuglumuhasebe.appspot.com',
    iosBundleId: 'com.fisis.saglamoglu.muhasebe.saglamogluMuhasebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF-bVy6JD6i8YBnsXFEsdOs9mUky-x2uQ',
    appId: '1:985947424591:ios:6ecca0f639550b7d49e73a',
    messagingSenderId: '985947424591',
    projectId: 'saglamuglumuhasebe',
    storageBucket: 'saglamuglumuhasebe.appspot.com',
    iosBundleId: 'com.fisis.saglamoglu.muhasebe.saglamogluMuhasebe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHXpdmTUPhrbhPO9rUDAeGf-bea0SRQQA',
    appId: '1:985947424591:web:53d2febca2887fdb49e73a',
    messagingSenderId: '985947424591',
    projectId: 'saglamuglumuhasebe',
    authDomain: 'saglamuglumuhasebe.firebaseapp.com',
    storageBucket: 'saglamuglumuhasebe.appspot.com',
  );
}
